import turtle



py = turtle.Turtle()
py.getscreen().bgcolor("#ff00ff")
py.penup()
py.sety(-300)
py.pendown()

py.color("blue")

py.begin_fill()
py.circle(300)
py.end_fill()

py.penup()
py.setpos(-110, -70)
py.pendown()

py.right(90)
py.color("yellow")
def logo(py):
	py.begin_fill()
	py.forward(140)

	py.circle(20, 90)

	py.forward(160)

	py.circle(50, 70)

	py.forward(100)
	py.left(110)
	py.forward(150)
	py.right(90)
	py.forward(10)
	py.right(90)
	py.forward(160)

	py.circle(50, 90)
	py.forward(70)
	py.circle(50, 90)
	py.forward(15)
	py.left(90)
	py.forward(30)
	py.circle(-50, 90)
	py.forward(156)
	py.circle(50, 90)
	py.forward(30)
	py.end_fill()
logo(py)
py.penup()
py.setpos(138, 75)
py.right(180)
py.pendown()

py.color("white")
logo(py)

py.penup()
py.color("blue")
py.begin_fill()
py.setpos(-60, 168)
py.pendown()
py.circle(-16)
py.end_fill()

py.penup()
py.color("blue")
py.begin_fill()
py.setpos(58, -163)
py.pendown()
py.circle(-16)
py.end_fill()
py.penup()
py.color("red")
py.setpos(-100, 38)
py.pendown()
py.write("JBoss", True, font=("Times new Roman", 20, "normal"))
py.begin_fill()
py.penup()
py.setpos(-100, 80)
py.pendown()

py.circle(-5)
py.end_fill()
py.penup()
py.setpos(-115, 70)
py.pendown()
py.begin_fill()
py.circle(-6)
py.end_fill()
py.penup()
py.setpos(-125, 55)
py.pendown()
py.begin_fill()
py.circle(-7)
py.end_fill()
py.penup()
py.setpos(-120, 38)
py.pendown()
py.begin_fill()
py.circle(-8)
py.end_fill()
py.penup()
py.setpos(-107, 23)
py.pendown()
py.begin_fill()
py.circle(-9)
py.end_fill()
py.ht()
turtle.done()